### ISSUE TITLE
Hyper-parameter tuning (Kornli)

### ISSUE THREAD

**Issue by SeungHyunChoii** [toriving/text-classification-transformers#2]
먼저 좋은 정보 감사합니다. colab 예제를 통해 Kornli 성능 실험하고 있습니다. 
혹시 더 좋은 성능을 위해 Hyper-parameter tuning 한 예제 적용도 colab에서 적용해주실 수 있을까요?

**Comment by toriving** [comment]
안녕하세요.

먼저 이슈를 늦게 확인하게 되어 답변이 늦어죄송합니다.
현재 제공되는 데이터 및 모델에 대해서는 Hyper-parameter tuning을 따로 하지 않았습니다.
다만 제가 리포팅해놓은 스코어의 하이퍼 파라미터의 경우는 `https://github.com/toriving/text-classification-transformers/tree/master/sh` 에서 확인하실 수 있습니다.
또한 colab에서도 같은 값이 사용되었습니다.

감사합니다.
